package handler

const (
	ROOM_CREATED             = "ROOM_CREATED"
	SUCCESS_JOIN_ROOM        = "SUCCESS_JOIN_ROOM"
	SOMEONE_JOIN_ROOM        = "SOMEONE_JOIN_ROOM"
	ROOM_NOT_FOUND           = "ROOM_NOT_FOUND"
	ROOM_FULL                = "ROOM_FULL"
	ROOM_FULL_READY_TO_START = "ROOM_FULL_READY_TO_START_GAME"
	GAME_START               = "GAME_START"
	ROUND_START              = "ROUND_START"
	SOMEONE_FINISH           = "SOMEONE_FINISH"
	ROUND_END                = "ROUND_END"
	GAME_END                 = "GAME_END"
	SOLUTION_ACCEPTED        = "SOLUTION_ACCEPTED"
	SOLUTION_REJECTED        = "SOLUTION_REJECTED"
)
